"use client";
import {useEffect,useMemo,useState} from "react";
import {ResultMap,buildStandings,completedMatches,flags,latestCompletedMatch,matchTeams,matches,nextPlayableMatch,pointAwardsForMatch,stageLabels,type Match} from "@/lib/quiniela";
type Tab="tabla"|"partidos"|"reglas";type Guest={name:string;emoji:string;color:string};
const nouns=["Ajolote","Nopal","Jaguar","Portero","Taco","Coyote","Volcán","Trompo"],adjectives=["Galáctico","Atómico","Místico","Relámpago","Cósmico","Bravo","Neón","Épico"],emojis=["🦎","🌵","🐆","🧤","🌮","🐺","🌋","⚽"],colors=["#c6ff3d","#13d9c0","#ffcb43","#ff7966","#b9c8ff","#ff9bdd"];
const medals={1:{icon:"🥇",label:"Oro",className:"gold"},2:{icon:"🥈",label:"Plata",className:"silver"},3:{icon:"🥉",label:"Bronce",className:"bronze"}} as const;
const monthMap:Record<string,number>={JUN:5,JUL:6};
const makeGuest=():Guest=>{const i=Math.floor(Math.random()*nouns.length);return{name:`${nouns[i]} ${adjectives[Math.floor(Math.random()*adjectives.length)]} ${Math.floor(10+Math.random()*90)}`,emoji:emojis[i],color:colors[Math.floor(Math.random()*colors.length)]}};
function timeInfo(match:Match){const [dayText,monthText]=match.date.split(" "),[h,m]=match.time.split(":").map(Number),day=Number(dayText),month=monthMap[monthText]??6;const mx=new Date(Date.UTC(2026,month,day,h+6,m));const dk=new Date(mx.getTime()+8*60*60*1000);const plus=dk.getUTCDate()!==mx.getUTCDate()?" +1":"";return{cdmx:match.time,dk:`${String(dk.getUTCHours()).padStart(2,"0")}:${String(dk.getUTCMinutes()).padStart(2,"0")}${plus}`}}
function TimeBlock({match}:{match:Match}){const t=timeInfo(match);return <span className="time-block"><b>CDMX {t.cdmx}</b><b>Dinamarca {t.dk}</b></span>}
export default function Home(){
 const[tab,setTab]=useState<Tab>("tabla"),[results,setResults]=useState<ResultMap>({}),[source,setSource]=useState("Sincronizando"),[guest,setGuest]=useState<Guest|null>(null),[recap,setRecap]=useState(""),[loading,setLoading]=useState(false),[selectedId,setSelectedId]=useState<string|null>(null),[copied,setCopied]=useState(false);
 useEffect(()=>{const raw=localStorage.getItem("quiniela-guest-v1");if(raw){try{setGuest(JSON.parse(raw));return}catch{}}const g=makeGuest();localStorage.setItem("quiniela-guest-v1",JSON.stringify(g));setGuest(g)},[]);
 useEffect(()=>{let active=true;const sync=async()=>{try{const res=await fetch("/api/results",{cache:"no-store"}),data=await res.json();if(!active)return;setResults(data.results||{});setSource(data.source==="supabase"?"Datos en vivo":data.source==="api-football"?"Actualiza cada 2 h":"Modo demo")}catch{if(active)setSource("Sin conexión")}};sync();const timer=setInterval(sync,60000);return()=>{active=false;clearInterval(timer)}},[]);
 const table=useMemo(()=>buildStandings(results),[results]),next=useMemo(()=>nextPlayableMatch(results),[results]),last=useMemo(()=>latestCompletedMatch(results),[results]),completed=useMemo(()=>completedMatches(results).length,[results]),awards=useMemo(()=>last?pointAwardsForMatch(last,results):[],[last,results]);
 const selected=table.find(p=>p.id===selectedId)||null,selectedIndex=selected?table.findIndex(p=>p.id===selected.id):-1;
 const selectedEvents=useMemo(()=>selected?completedMatches(results).filter(m=>!m.includedInBase&&!m.excluded).map(m=>{const teams=matchTeams(m,results),r=results[m.id]??m.baseResult,award=pointAwardsForMatch(m,results).find(a=>a.id===selected.id);return{match:m,teams,result:r,award,points:award?.awarded??0}}):[],[selected,results]);
 const extraPoints=selectedEvents.reduce((sum,item)=>sum+item.points,0),exactAfterCut=selectedEvents.filter(item=>item.award?.reason.includes("Marcador exacto")||item.award?.reason.includes("Empate exacto")).length,avg=selectedEvents.length?(extraPoints/selectedEvents.length).toFixed(1):"0.0";
 const moveSelected=(dir:number)=>{if(!table.length||selectedIndex<0)return;setSelectedId(table[(selectedIndex+dir+table.length)%table.length].id);setCopied(false)};
 useEffect(()=>{if(!selected)return;const prev=document.body.style.overflow;document.body.style.overflow="hidden";const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelectedId(null);if(e.key==="ArrowLeft")moveSelected(-1);if(e.key==="ArrowRight")moveSelected(1)};window.addEventListener("keydown",onKey);return()=>{document.body.style.overflow=prev;window.removeEventListener("keydown",onKey)}});
 const randomize=()=>{const g=makeGuest();localStorage.setItem("quiniela-guest-v1",JSON.stringify(g));setGuest(g)};
 const copySummary=async()=>{if(!selected)return;const text=`${selected.name}: ${selected.points} pts, posición ${selected.rank}, ${selected.exact} exactos. Sumó ${extraPoints} pts después del corte.`;try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{}};
 const share=async()=>{const text="Así va la quiniela familiar 👀";try{const res=await fetch("/api/share",{cache:"no-store"}),blob=await res.blob(),file=new File([blob],"tabla-quiniela.png",{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:"Quiniela Familiar 2026",text,files:[file]});return}}catch{}window.open(`https://wa.me/?text=${encodeURIComponent(`${text}\n${location.origin}`)}`,"_blank","noopener,noreferrer")};
 const ai=async()=>{setLoading(true);try{const res=await fetch("/api/recap",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({standings:table.slice(0,5),latest:last?{teams:matchTeams(last,results),result:results[last.id]??last.baseResult}:null})}),data=await res.json();setRecap(data.recap||data.error||"No fue posible generar el resumen.")}finally{setLoading(false)}};
 return <main className="page"><section className="app">
  <header className="topbar"><div className="brand"><div className="mark">Q</div><div><strong>Quiniela Familiar</strong><small>Mundial 2026 · no oficial</small></div></div><div className="top-actions"><span className="sync"><i/>{source}</span>{guest&&<button className="guest" onClick={randomize}><b style={{background:guest.color}}>{guest.emoji}</b><span>{guest.name}</span></button>}</div></header>
  <section className="hero compact-hero"><div><span className="eyebrow">Consulta tu lugar y cómo se mueve la tabla</span><h1>Mira en qué lugar vas y cómo se mueve la tabla.</h1><p>Consulta la clasificación actual, los últimos puntos otorgados y el siguiente partido del torneo en una sola vista.</p><div className="actions"><button className="primary" onClick={()=>setTab("tabla")}>Ver tabla ahora</button><button className="secondary" onClick={share}>Compartir por WhatsApp</button><button className="secondary" onClick={ai} disabled={loading}>{loading?"Escribiendo…":"Resumen con IA"}</button></div></div>
   <aside className="next"><span>Próximo partido</span>{next?(()=>{const t=matchTeams(next,results);return <><small>{stageLabels[next.stage]}</small><div className="teams"><div><b>{flags[t.home]}</b><strong>{t.home}</strong></div><i>VS</i><div><b>{flags[t.away]}</b><strong>{t.away}</strong></div></div><footer>{next.date}<TimeBlock match={next}/><em>{next.venue}</em></footer></>})():<p>Torneo terminado.</p>}</aside>
  </section>
  {recap&&<div className="recap"><div><span>Resumen automático</span><p>{recap}</p></div><button onClick={()=>setRecap("")}>×</button></div>}
  <section className="surface first-surface"><nav><button className={tab==="tabla"?"active":""} onClick={()=>setTab("tabla")}>Clasificación</button><button className={tab==="partidos"?"active":""} onClick={()=>setTab("partidos")}>Partidos</button><button className={tab==="reglas"?"active":""} onClick={()=>setTab("reglas")}>Reglas y premios</button></nav>
   {tab==="tabla"&&<div className="dashboard emphasis-first"><article className="panel ranking feature-ranking"><header><div><span>Clasificación general</span><h2>Así va la tabla</h2></div><b>{completed} de 31</b></header><div className="podium deluxe-podium">{table.slice(0,3).map(p=>{const meta=medals[p.rank as 1|2|3]??medals[3],tied=p.rank===2&&table.filter(x=>x.rank===2).length>1;return <button className={`podium-card deluxe ${meta.className}`} key={p.id} onClick={()=>setSelectedId(p.id)}><div className="medal">{meta.icon}</div><span className="position-label">{meta.label}{tied?" · empate":""}</span><div className="avatar-ring" style={{background:p.color}}>{p.short}</div><strong>{p.name}</strong><b>{p.points}<small> pts</small></b><span>{p.exact} marcadores exactos</span></button>})}</div><div className="rows">{table.slice(3).map(p=><button className="row" key={p.id} onClick={()=>setSelectedId(p.id)}><i>{p.rank}</i><div className="avatar" style={{background:p.color}}>{p.short}</div><div><strong>{p.name}</strong><span>{p.exact} marcadores exactos · tocar para detalle</span></div><b>{p.points}<small> pts</small></b></button>)}</div></article>
    <div className="stack"><article className="panel result"><span>Último resultado contabilizado</span>{last?(()=>{const t=matchTeams(last,results),r=results[last.id]??last.baseResult;return r&&<><div className="score"><div><b>{flags[t.home]}</b><strong>{t.home}</strong></div><i>{r.home}–{r.away}</i><div><b>{flags[t.away]}</b><strong>{t.away}</strong></div></div><p>La tabla ya incluye los puntos y marcadores exactos de este partido.</p></>})():<p>Aún no hay resultados.</p>}</article>
     <article className="panel audit log-panel"><span>Últimos puntos otorgados</span><h2>Qué recibió cada quien y por qué</h2><p>Toca cualquier participante para ver su desglose completo.</p><div className="point-log-list">{awards.length?awards.map(x=><div key={x.id} className="point-log-item"><div className="point-log-head"><div className="mini-avatar" style={{background:x.color}}>{x.short}</div><strong>{x.name}</strong><b>+{x.awarded}</b></div><em>{x.reason}</em></div>):<div className="point-log-empty">No hubo puntos o todavía no existen pronósticos cargados para este partido.</div>}</div></article></div></div>}
   {tab==="partidos"&&<div className="calendar">{Object.entries(stageLabels).map(([stage,label])=><section key={stage}><header><h2>{label}</h2><span>{matches.filter(m=>m.stage===stage).length} partidos</span></header><div>{matches.filter(m=>m.stage===stage).map(m=>{const t=matchTeams(m,results),r=results[m.id]??m.baseResult;return <article className={r?"finished":""} key={m.id}><small>Partido {m.id} · {m.excluded?"Excluido":r?"Final":"Pendiente"}</small><p><strong>{flags[t.home]} {t.home}</strong><b>{r?r.home:"–"}</b></p><p><strong>{flags[t.away]} {t.away}</strong><b>{r?r.away:"–"}</b></p><footer>{m.date}<TimeBlock match={m}/><em>{m.venue}</em></footer></article>})}</div></section>)}</div>}
   {tab==="reglas"&&<div className="rules"><article className="blue"><span>01</span><h2>Marcador exacto</h2><b>3 puntos</b><p>Coincide exactamente con el resultado de los 90 minutos.</p></article><article><span>02</span><h2>Ganador o clasificado</h2><b>1 punto</b><p>Cuando no hay exacto, se reconoce el equipo correcto.</p></article><article><span>03</span><h2>Empate exacto</h2><b>Hasta 4 puntos</b><p>3 por el empate exacto y 1 adicional por el clasificado.</p></article><article className="dark"><span>Bolsa total</span><h2>$1,800 MXN</h2><div><b>1.º $1,000</b><b>2.º $500</b><b>3.º $300</b></div></article></div>}
  </section><footer className="stats"><div><strong>$1,800</strong><span>Bolsa total</span></div><div><strong>9</strong><span>Participantes</span></div><div><strong>{completed}/31</strong><span>Partidos</span></div><div><strong>CDMX / DK</strong><span>Horarios</span></div></footer>
  {selected&&<div className="modal-backdrop" onClick={()=>setSelectedId(null)}><section className="player-modal upgraded-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelectedId(null)}>×</button><header><div className="avatar-ring big" style={{background:selected.color}}>{selected.short}</div><div><span>Desglose de puntos</span><h2>{selected.name}</h2><p>{selected.points} pts · posición {selected.rank} · {selected.exact} exactos</p></div></header><div className="modal-toolbar"><button onClick={()=>moveSelected(-1)}>← Anterior</button><button onClick={copySummary}>{copied?"Copiado":"Copiar resumen"}</button><button onClick={()=>moveSelected(1)}>Siguiente →</button></div><div className="modal-kpis"><div><strong>{selected.basePoints}</strong><span>pts base</span></div><div><strong>+{extraPoints}</strong><span>después del corte</span></div><div><strong>{exactAfterCut}</strong><span>exactos nuevos</span></div><div><strong>{avg}</strong><span>promedio</span></div></div><div className="base-summary"><strong>Lectura rápida</strong><span>Los puntos base vienen del corte inicial; abajo ves qué pasó partido por partido después de ese corte.</span></div><div className="breakdown-list upgraded-breakdown">{selectedEvents.length?selectedEvents.map(({match,teams,result,award,points})=><article key={match.id} className={points>0?"earned":"zero"}><small>Partido {match.id} · {stageLabels[match.stage]}</small><div><b>{teams.home} {result?.home}–{result?.away} {teams.away}</b><strong>{points>0?`+${points} pts`:"0 pts"}</strong></div><p>{award?.reason??"No sumó puntos en este partido."}</p></article>):<p className="empty-breakdown">Sin partidos adicionales después del corte base.</p>}</div></section></div>}
 </section></main>
}
