"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import RankingShareCard from "@/components/RankingShareCard";
import {participantPhotos} from "@/lib/participantPhotos";
import {ResultMap,buildStandings,completedMatches,flags,latestCompletedMatch,matchTeams,matches,nextPlayableMatch,pointAwardsForMatch,stageLabels,type Match} from "@/lib/quiniela";

type Tab="tabla"|"partidos"|"reglas";
type Guest={name:string;emoji:string;color:string};
type BaseValue=number|"NC";
type FixtureInfo={dateUtc?:string;status?:string;statusLong?:string;elapsed?:number|null;venue?:string;homeScore?:number|null;awayScore?:number|null;isLive?:boolean};
type FixtureMap=Record<string,FixtureInfo>;
type DetailKind="earned"|"zero"|"nc";

const nouns=["Ajolote","Nopal","Jaguar","Portero","Taco","Coyote","Volcán","Trompo"],adjectives=["Galáctico","Atómico","Místico","Relámpago","Cósmico","Bravo","Neón","Épico"],emojis=["🦎","🌵","🐆","🧤","🌮","🐺","🌋","⚽"],colors=["#c6ff3d","#13d9c0","#ffcb43","#ff7966","#b9c8ff","#ff9bdd"];
const medals=[{icon:"🥇",label:"Oro - 1er lugar",className:"gold"},{icon:"🥈",label:"Plata - 2do lugar",className:"silver"},{icon:"🥉",label:"Bronce - 3er lugar",className:"bronze"}] as const;
const monthMap:Record<string,number>={JUN:5,JUL:6};
const basePointMatrix:Record<string,Record<string,BaseValue>>={israel:{"76":3,"74":0,"75":3,"78":3,"77":1,"79":1,"80":1,"82":1,"81":3,"84":1},isra:{"76":1,"74":0,"75":3,"78":3,"77":1,"79":1,"80":1,"82":0,"81":1,"84":1},alfre:{"76":0,"74":0,"75":1,"78":3,"77":1,"79":1,"80":1,"82":3,"81":1,"84":1},liz:{"76":"NC","74":0,"75":3,"78":3,"77":1,"79":1,"80":1,"82":0,"81":1,"84":1},rebeca:{"76":1,"74":0,"75":0,"78":3,"77":1,"79":1,"80":1,"82":1,"81":1,"84":1},alfredito:{"76":1,"74":0,"75":0,"78":1,"77":1,"79":0,"80":3,"82":1,"81":1,"84":1},nuria:{"76":"NC","74":0,"75":1,"78":3,"77":1,"79":1,"80":1,"82":0,"81":0,"84":1},pedro:{"76":"NC","74":1,"75":0,"78":0,"77":1,"79":1,"80":1,"82":0,"81":0,"84":3},rebe:{"76":"NC","74":1,"75":1,"78":1,"77":0,"79":1,"80":1,"82":1,"81":1,"84":0}};

const makeGuest=():Guest=>{const i=Math.floor(Math.random()*nouns.length);return{name:`${nouns[i]} ${adjectives[Math.floor(Math.random()*adjectives.length)]} ${Math.floor(10+Math.random()*90)}`,emoji:emojis[i],color:colors[Math.floor(Math.random()*colors.length)]}};
const fmt=(date:Date,tz:string)=>new Intl.DateTimeFormat("es-MX",{timeZone:tz,day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",hour12:false}).format(date).replace(".","");
function fallbackDate(match:Match){const[dayText,monthText]=match.date.split(" "),[h,m]=match.time.split(":").map(Number);return new Date(Date.UTC(2026,monthMap[monthText]??6,Number(dayText),h+6,m))}
function timeInfo(match:Match,fixtures:FixtureMap){const date=fixtures[match.id]?.dateUtc?new Date(fixtures[match.id].dateUtc as string):fallbackDate(match);return{cdmx:fmt(date,"America/Mexico_City"),dk:fmt(date,"Europe/Copenhagen"),venue:fixtures[match.id]?.venue||match.venue}}
function TimeBlock({match,fixtures}:{match:Match;fixtures:FixtureMap}){const t=timeInfo(match,fixtures);return <span className="time-block"><b>CDMX {t.cdmx}</b><b>Dinamarca {t.dk}</b></span>}
function statusText(f?:FixtureInfo){if(!f)return"";if(f.status==="HT")return"Medio tiempo";if(f.isLive&&typeof f.elapsed==="number")return`Min ${f.elapsed}`;return f.statusLong||f.status||""}
function baseReason(value:BaseValue|undefined,teams:{home:string;away:string}){if(value==="NC")return"NC: pronóstico tardío o no contado en el corte maestro.";if(value===3)return`Marcador exacto registrado en el corte maestro para ${teams.home} vs ${teams.away}.`;if(value===1)return`Acierto de 1 punto registrado en el corte maestro para ${teams.home} vs ${teams.away}.`;return`No sumó puntos en el corte maestro para ${teams.home} vs ${teams.away}.`}
function Face({id,short,color,className}:{id:string;short:string;color:string;className:string}){const photo=participantPhotos[id];return <div className={`${className} ${photo?"face-photo":""}`} style={photo?{backgroundImage:`url(${photo})`,backgroundColor:color}:{background:color}}><span>{short}</span></div>}

export default function Home(){
 const shareCardRef=useRef<HTMLDivElement|null>(null);
 const[tab,setTab]=useState<Tab>("tabla"),[results,setResults]=useState<ResultMap>({}),[fixtures,setFixtures]=useState<FixtureMap>({}),[generatedAt,setGeneratedAt]=useState(""),[source,setSource]=useState("Sincronizando"),[guest,setGuest]=useState<Guest|null>(null),[recap,setRecap]=useState(""),[loading,setLoading]=useState(false),[selectedId,setSelectedId]=useState<string|null>(null),[copied,setCopied]=useState(false),[sharing,setSharing]=useState(false),[playerRecap,setPlayerRecap]=useState(""),[playerLoading,setPlayerLoading]=useState(false);
 useEffect(()=>{const raw=localStorage.getItem("quiniela-guest-v1");if(raw){try{setGuest(JSON.parse(raw));return}catch{}}const g=makeGuest();localStorage.setItem("quiniela-guest-v1",JSON.stringify(g));setGuest(g)},[]);
 useEffect(()=>{let active=true;const sync=async()=>{try{const res=await fetch("/api/results",{cache:"no-store"}),data=await res.json();if(!active)return;setResults(data.results||{});setFixtures(data.fixtures||{});setGeneratedAt(data.generatedAt||new Date().toISOString());setSource(data.hasLive?"Marcador en vivo":data.source==="supabase"?"Datos en vivo":data.source==="api-football"?"Actualiza solo":"Modo demo")}catch{if(active)setSource("Sin conexión")}};sync();const timer=setInterval(sync,30000);return()=>{active=false;clearInterval(timer)}},[]);
 const table=useMemo(()=>buildStandings(results),[results]),next=useMemo(()=>nextPlayableMatch(results),[results]),last=useMemo(()=>latestCompletedMatch(results),[results]),completed=useMemo(()=>completedMatches(results).length,[results]),awards=useMemo(()=>last?pointAwardsForMatch(last,results):[],[last,results]);
 const live=useMemo(()=>matches.map(match=>({match,fixture:fixtures[match.id]})).find(item=>item.fixture?.isLive)??null,[fixtures]);
 const selected=table.find(p=>p.id===selectedId)||null,selectedIndex=selected?table.findIndex(p=>p.id===selected.id):-1,selectedPlace=selectedIndex>=0?selectedIndex+1:0;
 const selectedEvents=useMemo(()=>selected?completedMatches(results).filter(m=>!m.excluded).map(m=>{const teams=matchTeams(m,results),result=results[m.id]??m.baseResult,rawBase=m.includedInBase?basePointMatrix[selected.id]?.[m.id]:undefined,computed=pointAwardsForMatch(m,results).find(a=>a.id===selected.id),points=m.includedInBase?(rawBase==="NC"?0:Number(rawBase??0)):(computed?.awarded??0),label=rawBase==="NC"?"NC":points>0?`+${points} pts`:"0 pts",reason=m.includedInBase?baseReason(rawBase,teams):(computed?.reason??"No sumó puntos en este partido."),kind=(rawBase==="NC"?"nc":points>0?"earned":"zero") as DetailKind;return{match:m,teams,result,points,label,reason,kind}}):[],[selected,results]);
 const postCutPoints=selectedEvents.filter(item=>!item.match.includedInBase).reduce((sum,item)=>sum+item.points,0),baseRowsTotal=selectedEvents.filter(item=>item.match.includedInBase).reduce((sum,item)=>sum+item.points,0),avg=selected&&selectedEvents.length?(selected.points/selectedEvents.length).toFixed(1):"0.0";
 const moveSelected=(dir:number)=>{if(!table.length||selectedIndex<0)return;setSelectedId(table[(selectedIndex+dir+table.length)%table.length].id);setCopied(false);setPlayerRecap("")};
 useEffect(()=>{setPlayerRecap("")},[selectedId]);
 useEffect(()=>{if(!selected)return;const prev=document.body.style.overflow;document.body.style.overflow="hidden";const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelectedId(null);if(e.key==="ArrowLeft")moveSelected(-1);if(e.key==="ArrowRight")moveSelected(1)};window.addEventListener("keydown",onKey);return()=>{document.body.style.overflow=prev;window.removeEventListener("keydown",onKey)}});
 const randomize=()=>{const g=makeGuest();localStorage.setItem("quiniela-guest-v1",JSON.stringify(g));setGuest(g)};
 const copySummary=async()=>{if(!selected)return;const text=`${selected.name}: ${selected.points} pts, posición ${selectedPlace}, ${selected.exact} exactos. Base ${selected.basePoints} pts + ${postCutPoints} pts después del corte.`;try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{}};
 const createImage=async()=>{if(!shareCardRef.current)return null;const {toPng}=await import("html-to-image");return toPng(shareCardRef.current,{cacheBust:true,pixelRatio:2,backgroundColor:"#07131f"})};
 const downloadImage=async()=>{setSharing(true);try{const dataUrl=await createImage();if(!dataUrl)return;const a=document.createElement("a");a.href=dataUrl;a.download="tabla-quiniela.png";document.body.appendChild(a);a.click();a.remove()}finally{setSharing(false)}};
 const share=async()=>{setSharing(true);try{const dataUrl=await createImage();if(!dataUrl)return;const blob=await(await fetch(dataUrl)).blob(),file=new File([blob],"tabla-quiniela.png",{type:"image/png"});if(navigator.canShare?.({files:[file]})){await navigator.share({title:"Quiniela Familiar 2026",text:"Así va la tabla 👀",files:[file]});return}await downloadImage()}finally{setSharing(false)}};
 const ai=async()=>{setLoading(true);try{const res=await fetch("/api/recap",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({standings:table.slice(0,5),latest:last?{teams:matchTeams(last,results),result:results[last.id]??last.baseResult}:null,next:next?{teams:matchTeams(next,results),time:timeInfo(next,fixtures)}:null,live:live?{teams:matchTeams(live.match,results),score:{home:live.fixture?.homeScore,away:live.fixture?.awayScore},status:statusText(live.fixture)}:null})}),data=await res.json();setRecap(data.recap||"La tabla está actualizada. Revisa el siguiente partido para ver cómo puede moverse el podio.")}finally{setLoading(false)}};
 const playerAi=async()=>{if(!selected)return;setPlayerLoading(true);try{const res=await fetch("/api/recap",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({participant:{name:selected.name,points:selected.points,place:selectedPlace,exact:selected.exact,basePoints:baseRowsTotal,postCutPoints},events:selectedEvents.map(e=>({match:e.match.id,stage:stageLabels[e.match.stage],teams:e.teams,score:e.result?`${e.result.home}-${e.result.away}`:"-",points:e.points,reason:e.reason})).slice(-12)})}),data=await res.json();setPlayerRecap(data.recap||"No fue posible generar el resumen del participante.")}finally{setPlayerLoading(false)}};
 return <main className="page"><div className="share-card-capture"><div ref={shareCardRef}><RankingShareCard table={table} source={source} completed={completed} generatedAt={generatedAt?fmt(new Date(generatedAt),"America/Mexico_City"):undefined}/></div></div><section className="app">
  <header className="topbar"><div className="brand"><div className="mark">⚽</div><div><strong>Quiniela Familiar</strong><small>Mundial 2026 · no oficial</small></div></div><div className="top-actions"><span className="sync"><i/>{source}</span>{guest&&<button className="guest" onClick={randomize}><b style={{background:guest.color}}>{guest.emoji}</b><span>{guest.name}</span></button>}</div></header>
  <section className="hero compact-hero"><div><span className="eyebrow">Tabla lista para consultar y compartir</span><h1>Quiniela familiar en vivo.</h1><p>Resultados, marcador en vivo, horarios CDMX/Dinamarca, desglose de puntos e imagen lista para WhatsApp.</p><div className="actions"><button className="primary" onClick={()=>setTab("tabla")}>Ver tabla</button><button className="secondary" onClick={share} disabled={sharing}>{sharing?"Preparando…":"Compartir imagen"}</button><button className="secondary" onClick={downloadImage} disabled={sharing}>Descargar imagen</button><button className="secondary" onClick={ai} disabled={loading}>{loading?"Escribiendo…":"Resumen con IA"}</button></div></div>
   {live?(()=>{const t=matchTeams(live.match,results),f=live.fixture;return <aside className="next live-score"><span><i/> Marcador en vivo</span><small>{stageLabels[live.match.stage]} · {statusText(f)}</small><div className="live-teams"><div><b>{flags[t.home]}</b><strong>{t.home}</strong></div><em>{f?.homeScore??0}–{f?.awayScore??0}</em><div><b>{flags[t.away]}</b><strong>{t.away}</strong></div></div><footer><TimeBlock match={live.match} fixtures={fixtures}/><em>La tabla suma puntos cuando sea final.</em></footer></aside>})():<aside className="next"><span>Próximo partido</span>{next?(()=>{const t=matchTeams(next,results),time=timeInfo(next,fixtures);return <><small>{stageLabels[next.stage]}</small><div className="teams"><div><b>{flags[t.home]}</b><strong>{t.home}</strong></div><i>VS</i><div><b>{flags[t.away]}</b><strong>{t.away}</strong></div></div><footer><TimeBlock match={next} fixtures={fixtures}/><em>{time.venue}</em></footer></>})():<p>Torneo terminado.</p>}</aside>}
  </section>
  {recap&&<div className="recap"><div><span>Resumen automático</span><p>{recap}</p></div><button onClick={()=>setRecap("")}>×</button></div>}
  <section className="surface first-surface"><nav><button className={tab==="tabla"?"active":""} onClick={()=>setTab("tabla")}>Clasificación</button><button className={tab==="partidos"?"active":""} onClick={()=>setTab("partidos")}>Partidos</button><button className={tab==="reglas"?"active":""} onClick={()=>setTab("reglas")}>Reglas y premios</button></nav>
   {tab==="tabla"&&<div className="dashboard emphasis-first"><article className="panel ranking feature-ranking"><header><div><span>Clasificación general</span><h2>Así va la tabla</h2></div><b>{completed} de 31</b></header><div className="podium deluxe-podium">{table.slice(0,3).map((p,i)=>{const meta=medals[i]??medals[2];return <button className={`podium-card deluxe ${meta.className}`} key={p.id} onClick={()=>setSelectedId(p.id)}><div className="medal">{meta.icon}</div><span className="position-label">{meta.label}</span><Face id={p.id} short={p.short} color={p.color} className="avatar-ring"/><strong>{p.name}</strong><b>{p.points}<small> pts</small></b><span>{p.exact} marcadores exactos</span></button>})}</div><div className="rows">{table.slice(3).map((p,i)=><button className="row" key={p.id} onClick={()=>setSelectedId(p.id)}><i>{i+4}</i><Face id={p.id} short={p.short} color={p.color} className="avatar"/><div><strong>{p.name}</strong><span>{p.exact} exactos · tocar para detalle</span></div><b>{p.points}<small> pts</small></b></button>)}</div></article>
    <div className="stack"><article className="panel result"><span>Último resultado contabilizado</span>{last?(()=>{const t=matchTeams(last,results),r=results[last.id]??last.baseResult;return r&&<><div className="score"><div><b>{flags[t.home]}</b><strong>{t.home}</strong></div><i>{r.home}–{r.away}</i><div><b>{flags[t.away]}</b><strong>{t.away}</strong></div></div><p>La tabla ya incluye los puntos de este partido.</p></>})():<p>Aún no hay resultados.</p>}</article>
     <article className="panel audit log-panel"><span>Últimos puntos otorgados</span><h2>Quién sumó y por qué</h2><p>Toca cualquier participante para ver su auditoría completa.</p><div className="point-log-list">{awards.length?awards.map(x=><div key={x.id} className="point-log-item"><div className="point-log-head"><Face id={x.id} short={x.short} color={x.color} className="mini-avatar"/><strong>{x.name}</strong><b>+{x.awarded}</b></div><em>{x.reason}</em></div>):<div className="point-log-empty">No hubo puntos o todavía no existen pronósticos cargados para este partido.</div>}</div></article></div></div>}
   {tab==="partidos"&&<div className="calendar">{Object.entries(stageLabels).map(([stage,label])=><section key={stage}><header><h2>{label}</h2><span>{matches.filter(m=>m.stage===stage).length} partidos</span></header><div>{matches.filter(m=>m.stage===stage).map(m=>{const t=matchTeams(m,results),r=results[m.id]??m.baseResult,f=fixtures[m.id],time=timeInfo(m,fixtures),liveNow=f?.isLive,homeScore=liveNow?(f?.homeScore??0):r?r.home:"–",awayScore=liveNow?(f?.awayScore??0):r?r.away:"–";return <article className={liveNow?"live-fixture":r?"finished":""} key={m.id}><small>Partido {m.id} · {m.excluded?"Excluido":liveNow?`En vivo · ${statusText(f)}`:r?"Final":"Pendiente"}</small><p><strong>{flags[t.home]} {t.home}</strong><b>{homeScore}</b></p><p><strong>{flags[t.away]} {t.away}</strong><b>{awayScore}</b></p><footer><TimeBlock match={m} fixtures={fixtures}/><em>{liveNow?"Marcador en vivo":time.venue}</em></footer></article>})}</div></section>)}</div>}
   {tab==="reglas"&&<div className="rules"><article className="blue"><span>01</span><h2>Marcador exacto</h2><b>3 puntos</b><p>Coincide exactamente con el resultado de los 90 minutos.</p></article><article><span>02</span><h2>Ganador o clasificado</h2><b>1 punto</b><p>Cuando no hay exacto, se reconoce el equipo correcto.</p></article><article><span>03</span><h2>Empate exacto</h2><b>Hasta 4 puntos</b><p>3 por el empate exacto y 1 adicional por el clasificado.</p></article><article className="dark"><span>Bolsa total</span><h2>$1,800 MXN</h2><div><b>1.º $1,000</b><b>2.º $500</b><b>3.º $300</b></div></article></div>}
  </section><footer className="stats"><div><strong>$1,800</strong><span>Bolsa total</span></div><div><strong>9</strong><span>Participantes</span></div><div><strong>{completed}/31</strong><span>Partidos</span></div><div><strong>{live?"Live":"CDMX / DK"}</strong><span>{live?"Marcador activo":"Horarios"}</span></div></footer>
 </section>{selected&&<div className="modal-backdrop" onClick={()=>setSelectedId(null)}><section className="player-modal upgraded-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelectedId(null)}>×</button><header><Face id={selected.id} short={selected.short} color={selected.color} className="avatar-ring big"/><div><span>Desglose de puntos</span><h2>{selected.name}</h2><p>{selected.points} pts · posición {selectedPlace} · {selected.exact} exactos</p></div></header><div className="modal-toolbar"><button onClick={()=>moveSelected(-1)}>← Anterior</button><button onClick={copySummary}>{copied?"Copiado":"Copiar resumen"}</button><button onClick={()=>moveSelected(1)}>Siguiente →</button></div><div className="modal-kpis"><div><strong>{selected.points}</strong><span>total actual</span></div><div><strong>{baseRowsTotal}</strong><span>pts de corte</span></div><div><strong>+{postCutPoints}</strong><span>después del corte</span></div><div><strong>{avg}</strong><span>promedio</span></div></div><div className="participant-ai"><button onClick={playerAi} disabled={playerLoading}>{playerLoading?"Analizando…":"Resumen IA del participante"}</button>{playerRecap&&<p>{playerRecap}</p>}</div><div className="base-summary"><strong>Auditoría completa</strong><span>Todos los partidos finalizados: corte maestro + actualizaciones posteriores.</span></div><div className="breakdown-list upgraded-breakdown">{selectedEvents.length?selectedEvents.map(({match,teams,result,label,reason,kind})=><article key={match.id} className={kind}><small>Partido {match.id} · {stageLabels[match.stage]}{match.includedInBase?" · corte maestro":""}</small><div><b>{teams.home} {result?.home}–{result?.away} {teams.away}</b><strong>{label}</strong></div><p>{reason}</p></article>):<p className="empty-breakdown">Sin partidos finalizados para mostrar.</p>}</div></section></div>}</main>
}
